dashboards/urls.py
from django.urls import path
from . import views

app_name = 'dashboards'

urlpatterns = [
    path('',views.create,name="create"),
    path('new/',views.new,name="new"),
    path('<int:pk>/',views.detail,name="detail"),
    path('<int:pk>/update/',views.update,name="update"),
    path('delete/<int:pk>/',views.delete,name="delete"),
]

newproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('guestbooks/',include('guestbooks.urls')),
    path('posts/',include('posts.urls')),
    path('dashboards/',include('dashboards.urls')),
    path('tables/',include('tables.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('new/',views.new,name='new'),
    path('create/',views.create,name='create'),
    path('delete/<int:pk>',views.delete,name='delete'),
]

dashboards/models.py
from django.db import models

# Create your models here.

class Dashboard(models.Model):
    title = models.CharField(null=True,max_length=20)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(null=True,auto_now_add=True)
    update_at = models.DateTimeField(null=True,auto_now=True)
    image = models.ImageField(upload_to='images/', blank=True)

dashboards/forms.py
from django import forms
from .models import Dashboard
class DashboardForm(forms.ModelForm):

    class Meta:
        model = Dashboard
        fields = '__all__'

        

dashboards/views.py
from django.shortcuts import render, redirect
from .models import Dashboard
from .forms import DashboardForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

# def index(request):
#     dashboardForm = DashboardForm()
#     context ={
#         'dashboardForm' : dashboardForm
#     }
#     return render(request,'dashboards/index.html',context)

@login_required
def create(request):  
    if request.method =='POST':
        dashboardForm = DashboardForm(request.POST,request.FILES)
        if dashboardForm.is_valid():
            dashboardForm.save()
            messages.success(request, '게시글을 작성하였습니다.')
            return redirect('dashboards:new')
    else:
        dashboardForm = DashboardForm()
    context = {
        'dashboardForm' : dashboardForm
    }
    return render(request,'dashboards/index.html',context)
    
    

def new(request):
    dashboards = Dashboard.objects.order_by('title')
    context ={
        'dashboards' : dashboards
    }
    return render(request,'dashboards/new.html',context)

def detail(request,pk):
    dashboards = Dashboard.objects.get(pk=pk)
    context = {
        'dashboards' : dashboards
    }
    return render(request,'dashboards/detail.html',context)

@login_required
def update(request,pk):
    dashboard = Dashboard.objects.get(pk=pk)
    if request.method =='POST':
        dashboardForm = DashboardForm(request.POST,instance=dashboard)
        if dashboardForm.is_valid():
            dashboardForm.save()
            return redirect('dashboards:new')
    else:
           dashboardForm = DashboardForm(instance=dashboard)
    context= {
        'dashboardForm' : dashboardForm
    }
    return render(request,'dashboards/update.html',context)

def delete(request,pk):
    dashboard = Dashboard.objects.get(pk=pk)
    dashboard.delete()
    return redirect('dashboards:new')

dashboards/templates/dashboards/detail.html
{% extends 'base.html' %}

{% block content %}
{{ dashboards.pk }} 번째 글
{{ dashboards.title }} {{ dashboards.content }} |{{ dashboards.update }}
<img src="{{ dashboards}}
<a href="{% url 'dashboards:update' dashboards.pk %}">수정하기</a>
{% endblock %}

dashboards/templates/dashboards/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
{% load static %}
<div class="container my-5"><h1>글쓰기</h1></div>
<div class="container my-5">
    <form action="{% url 'dashboards:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ dashboardForm.as_p }}
        <input type="submit">
    </form>
</div>
{% endblock %}

dashboards/templates/dashboards/new.html
{% extends 'base.html' %}

{% block content %}
<h1>게시판</h1>
<a href="{% url 'dashboards:create' %}">글쓰기</a>
<ul>
{% for dashboard in dashboards %}
    <li>
        <p>{{ dashboard.title }} | {{ dashboard.content }} | {{ dashboard.created_at }}</p>
        <a href="{% url 'dashboards:detail' dashboard.pk %}">상세보기</a>
        <a href="{% url 'dashboards:delete' dashboard.pk %}">삭제하기</a>
        <a href="{% url 'dashboards:update' dashboard.pk %}">수정하기</a>
        <hr>
    </li>
{% endfor %}

</ul>
{% endblock %}

dashboards/templates/dashboards/update.html
{% extends 'base.html' %}

{% block content %}
<h1>글 수정하기</h1>
<form action ='' method="POST">
    {% csrf_token %}
    {{ dashboardForm.as_p}}
    <input type="submit" value="수정">
</form>
{% endblock %}