accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<int:pk>/',views.detail,name='detail'),
    path('update/',views.update,name='update'),
    path('password/',views.passwordChange,name='passwordChange'),
    path('delete/',views.delete,name='delete'),
]

newproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('guestbooks/',include('guestbooks.urls')),
    path('posts/',include('posts.urls')),
    path('dashboards/',include('dashboards.urls')),
    path('tables/',include('tables.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('new/',views.new,name='new'),
    path('create/',views.create,name='create'),
    path('delete/<int:pk>',views.delete,name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = '__all__'

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.

def signup(request):
    if request.method=='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboards:create')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/signup.html',context)

def detail(request,pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user' :user
    }
    return render(request,'accounts/detail.html',context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())            
            return redirect(request.GET.get('next') or 'dashboards:new')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/login.html',context)

def logout(request):
    auth_logout(request)
    return redirect('dashboards:new')


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST,instance=request.user)
        if form.is_valid():
            form.save()           
            return redirect('accounts:detail',request.user.pk)
    else:
        form = CustomUserChangeForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/login.html',context)

def passwordChange(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)       
            return redirect('dashboards:new')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form
    }
    return render(request,'accounts/passwordChange.html',context)


def delete(request):
    request.user.delete()
    auth_logout(request) 
    return redirect('dashboards:new')

accounts/templates/accounts/detail.html
{% extends 'base.html' %}


{% block content %}
{{ user.username }}님 환영합니다
<a href="{% url 'accounts:update' %}">프로필 수정</a>
<a href="{% url 'accounts:passwordChange' %}">비밀번호 변경</a>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<p1>로그인 기능확인</p1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

accounts/templates/accounts/passwordChagne.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<p1>비밀번호 변경</p1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<p1>회원가입 기능확인</p1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<p1>프로필 수정</p1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}