guestbooks/urls.py
from django.urls import path
from . import views

app_name = 'guestbooks'


urlpatterns = [
    path('index/',views.index, name="index"),
    path('create/',views.create,name="create"),
]

newproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('guestbooks/',include('guestbooks.urls')),
    path('posts/',include('posts.urls')),
    path('dashboards/',include('dashboards.urls')),
    path('tables/',include('tables.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('new/',views.new,name='new'),
    path('create/',views.create,name='create'),
    path('delete/<int:pk>',views.delete,name='delete'),
]

guestbooks/models.py
from django.db import models
# Create your models here.

class Guestbook(models.Model):
    content = models.TextField()
    

guestbooks/forms.py
from django import forms
from .models import Guestbook

class GuestbookForm(forms.ModelForm):

    class Meta:
        model = Guestbook
        fields = '__all__'

guestbooks/views.py
from django.shortcuts import render
from .models import Guestbook

def index(request):
    guestbook = Guestbook.objects.all()
    context = {
        'guestbook' : guestbook,
    }
    return render(request,'guestbooks/index.html',context)

def create(request):
    content = request.POST.get('content')
    context ={
        'content' : content,
    }
    Guestbook.objects.create(content=content)

    return render(request,'guestbooks/create.html',context)
# Create your views here.

guestbooks/templates/guestbooks/create.html
{% extends 'base.html' %}

{% block content %}
<h1>글이 작성되었습니다.</h1>
<p>작성내용 : {{ content }}</p>
<a href ="{% url 'guestbooks:index' %}">돌아가기</a>
{% endblock %}

guestbooks/templates/guestbooks/index.html
{% extends 'base.html' %}

{% block content %}
<h1>글을 작성해주세요.</h1>
<form action="{% url 'guestbooks:create' %}" method="Post">
    {% csrf_token %}
    <input type="text" name ="content">
    <input type="submit">
</form>
{% for content in guestbook %}
<p>{{ content.content }}</p>
{% endfor %}
{% endblock %}