accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<int:pk>/',views.detail,name='detail'),
    path('update/',views.update,name='update'),
    path('password/',views.passwordChange,name='passwordChange'),
    path('delete/',views.delete,name='delete'),
]

newproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('guestbooks/',include('guestbooks.urls')),
    path('posts/',include('posts.urls')),
    path('dashboards/',include('dashboards.urls')),
    path('tables/',include('tables.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('new/',views.new,name='new'),
    path('create/',views.create,name='create'),
    path('delete/<int:pk>',views.delete,name='delete'),
]

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <div class="container my-5">
        <title>Document</title>
        {{ user.username }}
        {% if request.user.is_authenticated %} 
            <a href="{% url 'accounts:logout' %}">로그아웃</a>
            <a href="{% url 'accounts:delete' %}">회원 탈퇴</a>
        {% else %}
            <a href="{% url 'accounts:signup' %}">회원가입</a>
            <a href="{% url 'accounts:login' %}">로그인</a>
        {% endif %}
    </div>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
</head>
<body>
 {% block content %}

 
 {% endblock content %}   